
insert into Antecedente VALUES ('PROBLEMA ACTUAL', 1,0 ,0,0,1)
insert into Antecedente VALUES ('Motivo de consulta', 1,0 ,1,1,0)
insert into Antecedente VALUES ('HÁBITOS', 1,0 ,2,0,1)
insert into Antecedente VALUES ('Alcohol', 1,1 ,4,0,0)
insert into Antecedente VALUES ('Marihuana', 1,1 ,5,0,0)
insert into Antecedente VALUES ('Tabaco', 1,1 ,6,0,0)
insert into Antecedente VALUES ('Cocaína', 1,1 ,7,0,0)
insert into Antecedente VALUES ('Drogas sintéticas', 1,1 ,8,0,0)
insert into Antecedente VALUES ('Opiáceos', 1,1 ,9,0,0)
insert into Antecedente VALUES ('Comentarios sobre hábitos', 1,0 ,10,1,0)
insert into Antecedente VALUES ('Medicación', 1,0 ,11,0,1)
insert into Antecedente VALUES ('Tratamiento farmacológico o medicación habitual:', 1,0 ,12,1,0)
insert into Antecedente VALUES ('Detalle de alergias medicamentosas', 1,0 ,13,1,0)
insert into Antecedente VALUES ('Posee alergias medicamentosas (alerta)', 1,1 ,14,0,0)
insert into Antecedente VALUES ('ANTECEDENTES PSIQUIÁTRICOS', 1,0 ,15,0,1)
insert into Antecedente VALUES ('Se realizó evaluación de riesgo suicida', 1,1 ,16,0,0)
insert into Antecedente VALUES ('Trastorno bipolar', 1,1 ,17,0,0)
insert into Antecedente VALUES ('Depresión mayor', 1,1 ,18,0,0)
insert into Antecedente VALUES ('Esquizofrenia', 1,1 ,19,0,0)
insert into Antecedente VALUES ('Deterioro cognitivo', 1,1 ,20,0,0)
insert into Antecedente VALUES ('Demencia', 1,1 ,21,0,0)
insert into Antecedente VALUES ('Dependencia a sustancias', 1,1 ,22,0,0)
insert into Antecedente VALUES ('Retraso mental', 1,1 ,23,0,0)
insert into Antecedente VALUES ('Trastorno de adaptación', 1,1 ,24,0,0)
insert into Antecedente VALUES ('Trastorno de ansiedad generalizada', 1,1 ,25,0,0)
insert into Antecedente VALUES ('Trastorno por ataque de pánico', 1,1 ,26,0,0)
insert into Antecedente VALUES ('Trastorno de estrés post traumático', 1,1 ,27,0,0)
insert into Antecedente VALUES ('Fobia social', 1,1 ,28,0,0)
insert into Antecedente VALUES ('Fobias específicas', 1,1 ,29,0,0)
insert into Antecedente VALUES ('Agorafobia', 1,1 ,30,0,0)
insert into Antecedente VALUES ('TOC', 1,1 ,31,0,0)
insert into Antecedente VALUES ('Trastorno de personalidad', 1,1 ,32,0,0)
insert into Antecedente VALUES ('Otros traumas:', 1,0 ,33,1,0)
insert into Antecedente VALUES ('Comentarios:', 1,0 ,34,1,0)
insert into Antecedente VALUES ('EXAMEN PSIQUIÁTRICO', 1,0 ,35,0,1)
insert into Antecedente VALUES ('Aspecto', 1,0 ,36,0,0)
insert into Antecedente VALUES ('Memoria', 1,0 ,37,0,0)
insert into Antecedente VALUES ('Actitud', 1,0 ,38,0,0)
insert into Antecedente VALUES ('Atención', 1,0 ,39,0,0)
insert into Antecedente VALUES ('Sensopercepsión', 1,0 ,40,0,0)
insert into Antecedente VALUES ('Porte', 1,0 ,41,0,0)
insert into Antecedente VALUES ('Conciencia', 1,0 ,42,0,0)
insert into Antecedente VALUES ('Orientación', 1,0 ,43,0,0)
insert into Antecedente VALUES ('Curso del pensamiento', 1,0 ,44,0,0)
insert into Antecedente VALUES ('Actividad', 1,0 ,45,0,0)
insert into Antecedente VALUES ('Contenido del pensamiento', 1,0 ,46,0,0)
insert into Antecedente VALUES ('Afectividad', 1,0 ,47,0,0)
insert into Antecedente VALUES ('Jucio', 1,0 ,48,0,0)
insert into Antecedente VALUES ('Sueño', 1,0 ,49,0,0)
insert into Antecedente VALUES ('Alimentación', 1,0 ,50,0,0)
insert into Antecedente VALUES ('Vida familiar', 1,0 ,51,0,0)
insert into Antecedente VALUES ('Reacciones antisociales', 1,0 ,52,0,0)
insert into Antecedente VALUES ('Conciencia de la enfermedad', 1,1 ,53,0,0)
insert into Antecedente VALUES ('ENTREVISTA DE ANAMNESIS', 1,0 ,54,0,1)
insert into Antecedente VALUES ('Nombre del padre', 1,0,55,0,0)
insert into Antecedente VALUES ('¿Vive?', 1,0,56,0,0)
insert into Antecedente VALUES ('Edad', 1,0,57,0,0)
insert into Antecedente VALUES ('Nivel de estudios', 1,0,58,0,0)
insert into Antecedente VALUES ('Ocupación', 1,0,59,0,0)
insert into Antecedente VALUES ('Nombre de la madre', 1,0,60,0,0)
insert into Antecedente VALUES ('¿Vive?', 1,0,61,0,0)
insert into Antecedente VALUES ('Edad', 1,0,62,0,0)
insert into Antecedente VALUES ('Nivel de estudios', 1,0,63,0,0)
insert into Antecedente VALUES ('Ocupación', 1,0,64,0,0)
insert into Antecedente VALUES ('Cantidad de hermanos', 1,0,65,0,0)
insert into Antecedente VALUES ('Miembros que conviven en el domicilio', 1,0,66,0,0)
insert into Antecedente VALUES ('Observaciones miembros que conviven', 1,0,67,1,0)
insert into Antecedente VALUES ('ENTREVISTA VINCULAR', 1,0,68,0,1)
insert into Antecedente VALUES ('Nombre del entrevistado', 1,0,69,0,0)
insert into Antecedente VALUES ('Vínculo con el paciente', 1,0,70,0,0)
insert into Antecedente VALUES ('Descripción de la problemática del paciente, tiempo y síntomas', 1,0,71,1,0)
insert into Antecedente VALUES ('Historia familiar y vincular del paciente, antecedentes y eventos significativos', 1,0,72,1,0)
insert into Antecedente VALUES ('¿Cuáles considera que son las preocupaciones del paciente?', 1,0,73,1,0)
insert into Antecedente VALUES ('Describa cómo es el vínculo con el paciente', 1,0,74,1,0)
