-- INSERT DE ATENCIONES
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-05 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (3,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-05 14:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-05 10:12:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (5,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-08 12:20:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-08 14:10:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-08 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-11 09:30:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (2,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-11 11:45:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (6,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-11 17:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
