-- INSERT DE ATENCIONES ESTA TOMANDO LA FECHA AL REVEZ AZURE
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 1, 'admin@gmail.com', '', '2020-01-05 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (3,'Primera consulta', 3, 'admin@gmail.com', '', '2020-01-05 14:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 1, 'admin@gmail.com', '', '2020-01-05 10:12:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (5,'Primera consulta', 4, 'admin@gmail.com', '', '2020-01-08 12:20:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 5, 'admin@gmail.com', '', '2020-01-08 14:10:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 2, 'admin@gmail.com', '', '2020-01-08 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 2, 'admin@gmail.com', '', '2020-01-11 09:30:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (2,'Primera consulta', 3, 'admin@gmail.com', '', '2020-01-11 11:45:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (6,'Primera consulta', 1, 'admin@gmail.com', '', '2020-01-11 17:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')


-- INSERT DE ATENCIONES
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 4, 'admin@gmail.com', '', '2020-02-05 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (3,'Primera consulta', 4, 'admin@gmail.com', '', '2020-02-05 14:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 3, 'admin@gmail.com', '', '2020-02-05 10:12:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (5,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-08 12:20:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 1, 'admin@gmail.com', '', '2020-02-08 14:10:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 2, 'admin@gmail.com', '', '2020-02-08 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 2, 'admin@gmail.com', '', '2020-02-11 09:30:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (2,'Primera consulta', 6, 'admin@gmail.com', '', '2020-02-11 11:45:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (6,'Primera consulta', 7, 'admin@gmail.com', '', '2020-02-11 17:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')


-- INSERT DE ATENCIONES
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 7, 'admin@gmail.com', '', '2019-12-05 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (3,'Primera consulta', 8, 'admin@gmail.com', '', '2019-12-05 14:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 5, 'admin@gmail.com', '', '2019-12-05 10:12:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (5,'Primera consulta', 5, 'admin@gmail.com', '', '2019-12-08 12:20:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 6, 'admin@gmail.com', '', '2019-12-08 14:10:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (4,'Primera consulta', 7, 'admin@gmail.com', '', '2019-12-08 18:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (1,'Primera consulta', 2, 'admin@gmail.com', '', '2019-12-11 09:30:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (2,'Primera consulta', 1, 'admin@gmail.com', '', '2019-12-11 11:45:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
INSERT INTO Atencion (Tratamiento_ID,Titulo,PacienteID,MedicoNombreUsuario,Medicacion,FechaHora,EstaEliminada,Diagnostico,Descripcion,Comentario)
VALUES (6,'Primera consulta', 4, 'admin@gmail.com', '', '2019-12-11 17:00:00', 0, 'Trastorno mental', 'Una obersvacion larga sobre la consulta del paciente', 'Ninguno')
