insert into Obrasocial VALUES ('Aca Salud')
insert into Obrasocial VALUES ('Omint')
insert into Obrasocial VALUES ('Swiss Medical')
insert into Obrasocial VALUES ('Osde')
insert into Obrasocial VALUES ('Sancor Salud')
insert into Obrasocial VALUES ('Asmperiv')
insert into Obrasocial VALUES ('Medifé')
insert into Obrasocial VALUES ('Galeno')
insert into Obrasocial VALUES ('DASUTeN')
insert into Obrasocial VALUES ('Previnca')
insert into Obrasocial VALUES ('Esencial')
