insert into Tratamiento VALUES ('Terapia cognitivo conductual', 'Plantilla del tratamiento?', null, null)
insert into Tratamiento VALUES ('Terapia cognitiva mindfulness', '', null, null)
insert into Tratamiento VALUES ('Terapia dialéctica conductual', 'Trastorno límite de la personalidad', null, null)
insert into Tratamiento VALUES ('Terapia de aceptación y compromiso', 'Teoría del marco relacional, lenguaje y cognición', null, null)
insert into Tratamiento VALUES ('Terapia sistémica', 'Problemas de familia y pareja', null, null)
insert into Tratamiento VALUES ('Terapia breve', '', null, null)
insert into Tratamiento VALUES ('Psicoterapia interpersonal', 'Conexiones entre los síntomas y los problemas interpersonales actuales', null, null)
insert into Tratamiento VALUES ('Biofeedback', 'Hacer que la persona sea consciente, en tiempo real, de los procesos psicológicos o fisiológicos que están teniendo lugar en su cuerpo', null, null)
insert into Tratamiento VALUES ('Terapia de reminiscencia', 'Demencias y enfermedades neurodegenerativas. Efectivo para pacientes con Alzheimer', null, null)
