// <auto-generated />
using System;
using Medisysnae.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Medisysnae.Migrations
{
    [DbContext(typeof(MedisysnaeContext))]
    [Migration("20191012213925_Entidades")]
    partial class Entidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Medisysnae.Models.Especialidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("ProfesionalNombreUsuario");

                    b.HasKey("ID");

                    b.HasIndex("ProfesionalNombreUsuario");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("Medisysnae.Models.Profesional", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<bool>("EsAdministrador");

                    b.Property<bool>("EstaHabilitado");

                    b.Property<string>("Matricula");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<int>("Telefono");

                    b.HasKey("NombreUsuario");

                    b.ToTable("Profesional");
                });

            modelBuilder.Entity("Medisysnae.Models.Tratamiento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CodigoNM");

                    b.Property<string>("Descripcion");

                    b.Property<int?>("EspecialidadID");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("EspecialidadID");

                    b.ToTable("Tratamiento");
                });

            modelBuilder.Entity("Medisysnae.Models.Especialidad", b =>
                {
                    b.HasOne("Medisysnae.Models.Profesional")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfesionalNombreUsuario");
                });

            modelBuilder.Entity("Medisysnae.Models.Tratamiento", b =>
                {
                    b.HasOne("Medisysnae.Models.Especialidad")
                        .WithMany("Tratamientos")
                        .HasForeignKey("EspecialidadID");
                });
#pragma warning restore 612, 618
        }
    }
}
